apiVersion: v1
kind: ConfigMap
metadata:
  name: crud-simple-config
data:
  DATASOURCE_URI: jdbc:postgresql://{{include "postgresql.fullname" .}}:{{.Values.postgresql.service.port}}/{{.Values.postgresql.postgresqlDatabase}}

