apiVersion: v1
kind: Secret
metadata:
  name: crud-simple-secret
type: Opaque
data:
  DATASOURCE_USERNAME: {{ b64enc .Values.postgresql.postgresqlUsername }}
  DATASOURCE_PASSWORD: {{ b64enc .Values.postgresql.postgresqlPassword }}
