apiVersion: v1
kind: Service
metadata:
  name: {{ include "crud-simple-chart.fullname" . }}
  labels:
  {{- include "crud-simple-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http-backend
      protocol: TCP
      name: http-backend
  selector:
  {{- include "crud-simple-chart.selectorLabels" . | nindent 4 }}
