apiVersion: v1
kind: Service
metadata:
  name: postgres-servicename
  labels:
    app: postgres-app-label
spec:
  type: NodePort
  ports:
   - port: 5432
  selector:
    app: postgres-app-label
 
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-statefulsetname
spec:
  serviceName: postgres-servicename
  replicas: 1
  selector:
    matchLabels:
      app: postgres-app-label
  template:
    metadata:
      labels:
        app: postgres-app-label
    spec:
      containers:
      - name: postgres-container
        image: postgres:latest
        ports:
        - containerPort: 5432
          name: postgres-port
        env:
          - name: POSTGRES_DB
            value: crudSimpleDb
          - name: POSTGRES_USER
            value: crudSimpleUser
          - name: POSTGRES_PASSWORD
            value: crudSimplePassword
        volumeMounts:
        - name: postgres-db-volume
          mountPath: /var/lib/postgresql/data
          subPath: postgres
  volumeClaimTemplates:
  - metadata:
      name: postgres-db-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard
      resources:
        requests:
          storage: 1Gi
