apiVersion: v1
kind: Service
metadata:
  name: crud-simple-service
spec:
  selector:
    app: crud-simple-label
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
